language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

script:
  - npm run build

after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    cd build;
    git init;
    git config user.name 'zhuweiyou';
    git config user.email 'i@zhuweiyou.com';
    git add .;
    git commit -m 'Deployed by <Travis CI>';
    git push https://${GH_TOKEN}@github.com/mtdhb/www.git master:gh-pages -f;
    fi

branches:
  only:
    - master
